name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1a802e74d7a4b285cb84cfa73dd8ae44e2f660c2bf123fae4e72d0a2e13bf32"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
