name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49b45721f72fb2584fbf73f71cc90eb0b5da32a06a79a950e0efa64af0ce2fd4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
