name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f5d84ac38bae9badadb9aad1e4620163c8f6f1ee77b6e3c2d4e790916309c8a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
