name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0e6f4e3d53752eae925b30b9091c99ee19398e7ba1db3d6e2c3b8c1ffa1e72"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
