name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbe93c0252fecc8e1d14ab3de9cbdc0197bf88c7cbebf81d2f6d4f00d81e5711"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
