name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "171cc916089076780c2f36a0bad2128626362380675c8af530c5dd6f19e90848"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
