name = "Valhelsia 6"
author = "ValhelsiaTeam"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7540153d9f9986a7c3ec4923fc4bf60c8ff2fa3166f47e69fd74bcdc1779aaa8"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
